"""add emotions field to Post

Revision ID: 7d7995ac3aea
Revises: d171bbc2e81b
Create Date: 2025-05-14 09:51:42.667865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d7995ac3aea'
down_revision = 'd171bbc2e81b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('emotions', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('emotions')

    # ### end Alembic commands ###
