"""delete label column to Post model

Revision ID: 87c8c6bbebb5
Revises: a7aa2a4f14bf
Create Date: 2025-05-07 22:53:31.670373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87c8c6bbebb5'
down_revision = 'a7aa2a4f14bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('label')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('label', sa.VARCHAR(length=64), nullable=True))

    # ### end Alembic commands ###
