"""Add sentiment column (nullable)

Revision ID: 8cbc44e378e1
Revises: 95d5ab301e7b
Create Date: 2025-05-04 18:08:51.275609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8cbc44e378e1'
down_revision = '95d5ab301e7b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sentiment', sa.String(length=64), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('sentiment')

    # ### end Alembic commands ###
