"""Add profile_completed to User

Revision ID: c6cadf49ff8f
Revises: fcc402e7f814
Create Date: 2025-05-11 10:33:40.273834

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6cadf49ff8f'
down_revision = 'fcc402e7f814'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        op.add_column('user', sa.Column('profile_completed', sa.Boolean(), server_default=sa.false(), nullable=False))


    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('profile_completed')

    # ### end Alembic commands ###
